C# final code.
kobiton/appium-script-generator pull request #8
Opened 2023-11-28 17:30 UTC by silverspoon19931120

## Summary

## Types of changes

_What types of changes does your code introduce to this project? Put an `x` in the boxes that apply._

- [ ] Bugfix.
- [x] New feature.
- [ ] Documentation update.

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the pull request. If you are unsure about any of them, do not hesitate to ask. We are here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) documentation.
- [x] I have rebased, and my remote branch is now up-to-date with the `master` branch of the upstream.
- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my changes are effective.
- [ ] I have added the necessary documentation (if appropriate).

## Further comments

2023-11-29 07:16 UTC, chuong777 requested changes

2023-11-29 07:16 UTC, chuong777 commented on src/templates/csharp/TestBase.cs
> +            return this.proxy != null ? this.proxy.currentCommandId : 0;
`this.proxy` has not been initialized

2023-11-29 07:16 UTC, chuong777 commented on src/templates/csharp/TestApp.cs
> +        {{testCases}}
The generated project has empty test case body. It should call FindOnlineDevice, Setup, RunTest
<img width="571" alt="image" src="https://github.com/kobiton/appium-script-generator/assets/15189024/1dff745e-9a7d-46ec-8640-ff3c9144d943">

2023-11-30 07:55 UTC, chuong777 requested changes

2023-11-30 07:55 UTC, chuong777 commented on src/templates/csharp/TestApp.cs
> +                throw e;
```suggestion
```

We need to call `Cleanup` to end session whether an exception occurs or not

2023-11-30 08:49 UTC, chuong777 requested changes

2023-11-30 08:49 UTC, chuong777 commented on src/templates/csharp/TestBase.cs
> +            }
SendKeys is not work as expected on Android. It send unexpected key code that make the application go to background.

Java implementation:
<img width="553" alt="image" src="https://github.com/kobiton/appium-script-generator/assets/15189024/5678f1f7-521d-44cb-8107-6e32ff075db1">

2023-11-30 12:15 UTC, chuong777 requested changes

2023-11-30 12:15 UTC, chuong777 commented on __tests__/resource/csharp-nunit-input.json
> +      "actionJson": "{\"command\":\"touchOnElement\",\"x\":\"0.387\",\"y\":\"0.430\",\"value\":\"beyoung.in\"}",
on an `touchOnElement ` we cannot have "value" field, please keep it as a separated test step with command "sendKey", sample: https://github.com/kobiton/appium-script-generator/blob/master/__tests__/resource/java-junit-input.json#L63

2023-11-30 12:15 UTC, chuong777 commented on src/services/csharp.js
> +                lines.push(new Line(`${elementVarName}.SendKeys(${this._getString(value)});`))
on "touchOnElement" step we cannot have "value" field for sendKeys command, it should be a separated step

2023-12-01 06:23 UTC, chuong777 requested changes

2023-12-05 13:10 UTC, chuong777 requested changes

2023-12-05 13:10 UTC, chuong777 commented on src/services/csharp.js
> +            lines.push(new Line(`Rectangle ${rectVarName} = GetWebElementRect(${elementVarName});`))
When context is NATIVE we will use other method (please check java code)

2023-12-06 08:27 UTC, chuong777 requested changes

2023-12-06 09:49 UTC, chuong777 requested changes

2023-12-06 09:49 UTC, chuong777 commented on __tests__/resource/csharp-nunit-input.json
> +      "actionJson": "{\"command\":\"press\",\"value\":\"Enter\"}",
```suggestion
      "actionJson": "{\"command\":\"press\",\"value\":\"ENTER\"}",
```
Please copy `testSteps` data from java file then run unit test again and check if project can be build

2023-12-06 09:49 UTC, chuong777 commented on src/handlers/generate-script.js
> +    //await removeDir(workingDir)
```suggestion
    await removeDir(workingDir)
```

2023-12-06 09:57 UTC, chuong777 requested changes

2023-12-06 09:57 UTC, chuong777 commented on src/templates/csharp/TestApp.cs
> +            );
This assertion is not work

2023-12-06 10:05 UTC, chuong777 requested changes

2023-12-06 10:05 UTC, chuong777 commented on src/templates/csharp/TestApp.cs
> +            );
This assertion is not working (wrong order of parameters). Please use `Assert.That `instead
```suggestion
            Assert.That(
                Config.KobitonApiKey, Is.Not.EqualTo("your_kobiton_api_key"),
                "Please update value for the KobitonApiKey constant first. See more at README.md file."
            );
```

2023-12-11 03:35 UTC, ledinhphuong requested changes

2023-12-11 03:35 UTC, ledinhphuong commented on __tests__/integration/generate-script.test.js
> +    __dirname, '../resource/nodejs-mocha-input.json')
Please correct the indentation

2023-12-11 03:35 UTC, ledinhphuong commented on src/templates/csharp/TestBase.cs
> +                appiumWebElement).Location.X,
```suggestion
                appiumWebElement.Location.X,
```

2023-12-11 03:47 UTC, ledinhphuong requested changes

2023-12-11 03:47 UTC, ledinhphuong commented on src/templates/csharp/TestBase.cs
> +            }
```suggestion
            if (driver != null)
            {
                driver.Quit();
            }

            if (proxy != null)
            {
                proxy.StopProxy();
            }
```

2023-12-11 09:36 UTC, chuong777 requested changes

2023-12-11 09:36 UTC, chuong777 commented on src/templates/csharp/Config.cs
> +        public enum DeviceSourceEnums { KOBITON, SAUCE_LABS }
Use PascalCasing for enum

2023-12-11 09:36 UTC, chuong777 commented on src/templates/csharp/TestBase.cs
> +        public enum PressTypes { HOME, BACK, POWER, APP_SWITCH, ENTER, DELETE }
Use PascalCasing for enum

2023-12-11 11:37 UTC, ledinhphuong requested changes

2023-12-11 12:25 UTC, chuong777 approved these changes

2023-12-11 12:38 UTC, ledinhphuong approved these changes

2023-12-11 14:02 UTC, merged

2024-03-08 05:17 UTC, silverspoon19931120 commented
HI Phoung?
How about my c# script works?
and can we continue next ruby script?
Frank said to me we can start in 22/ January.

2024-03-08 06:00 UTC, silverspoon19931120 commented
HI, Phoung, there?.